project_name: df

builds:
  - id: dlpretty
    main: ./dl/cmd/dlpretty
    binary: dlpretty

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: michaelquigley
    name: df
  draft: false
  prerelease: auto