name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23', '1.24']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go mod download
      - run: go test -v -race -coverprofile=coverage.out ./...
      - run: go run -race ./examples/df_bindunbind/main.go
      - run: go run -race ./examples/df_converters/main.go
      - run: go run -race ./examples/df_defaults/main.go
      - run: go run -race ./examples/df_inspect/main.go
      - run: go run -race ./examples/df_pointers/main.go
      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage.out

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - uses: golangci/golangci-lint-action@v4